In [2]:
import numpy as np
import pandas as pd



In [3]:
products = pd.read_csv("products.csv")
customers = pd.read_csv("customers.csv")
employees = pd.read_csv("employees.csv")


In [6]:
#Convert colums to numpy arrays
price = products["Price"].values
category_id = products["CategoryID"].values
customer_city = customers["CityID"].values


In [7]:
#Numpy array properties
print("Price Shape:", price.shape)
print("Price Size:", price.size)
print("Price Data Type:", price.dtype)


Price Shape: (452,)
Price Size: 452
Price Data Type: float64


In [8]:
#statistical opearations using numpys
print("Maximum Price:", np.max(price))
print("Minimum Price:", np.min(price))
print("Mean Price:", np.mean(price))
print("Total Price Sum:", np.sum(price))


Maximum Price: 99.8755
Minimum Price: 0.0449
Mean Price: 50.80147057522124
Total Price Sum: 22962.2647


In [9]:
#conditional filtering using numpys
above_avg_price = price[price > np.mean(price)]
above_avg_price[:10]


array([74.2988, 91.2329, 54.3055, 65.4771, 79.7184, 89.8573, 84.4219,
       95.0957, 54.7246, 85.9011])

In [10]:
#Discount caluclation using numpys
discount = np.random.choice([0, 0.05, 0.1, 0.2], size=len(price))
discounted_price = price * (1 - discount)
discounted_price[:10]


array([74.2988  , 86.671255,  8.681005, 54.3055  , 52.38168 , 75.73248 ,
       25.4696  , 71.88584 , 84.4219  , 95.0957  ])

In [11]:
#Quamtity and revenue caluclations using numpys 
quantity = np.random.randint(1, 10, size=len(price))
revenue = discounted_price * quantity

print("Total Revenue:", np.sum(revenue))
print("Average Revenue:", np.mean(revenue))


Total Revenue: 107602.54158
Average Revenue: 238.05872030973453


In [12]:
#Sorting Revenue
sorted_revenue = np.sort(revenue)
sorted_revenue[-10:]


array([698.3217  , 709.74405 , 716.0742  , 757.0024  , 771.758055,
       798.64218 , 801.333   , 803.48796 , 808.1991  , 893.8737  ])

In [13]:
#category wise Revenue
unique_categories = np.unique(category_id)
category_revenue = {}

for cat in unique_categories:
    category_revenue[cat] = np.sum(revenue[category_id == cat])

category_revenue


{1: 13565.77025,
 2: 7752.004485000001,
 3: 9515.523520000002,
 4: 9863.56519,
 5: 8730.054115,
 6: 7109.40308,
 7: 11503.674790000001,
 8: 8173.448825,
 9: 11391.152794999998,
 10: 10160.667929999998,
 11: 9837.2766}

In [14]:
#Reshaping numpy arrays
revenue_matrix = revenue[:20].reshape(4, 5)
revenue_matrix


array([[ 74.2988  , 606.698785,  69.44804 ,  54.3055  , 366.67176 ],
       [ 75.73248 , 229.2264  , 359.4292  , 590.9533  , 285.2871  ],
       [ 45.32328 , 355.21632 , 158.04992 ,  23.3268  , 129.768   ],
       [155.96511 , 237.15828 , 133.36062 , 121.83156 , 231.93297 ]])

In [16]:
### NumPy Summary
#- NumPy was used for numerical computations on FreshMart datasets
#- Price, discount, quantity, and revenue were calculated efficiently
#- Statistical and conditional operations were applied using NumPy
#- NumPy improved performance and reduced loop usage
